return {}
-- return {
--   "akinsho/toggleterm.nvim",
--   version = "*",
--   opts = {
--     size = 20,
--     open_mapping = [[<c-\>]],
--     direction = "horizontal",
--     start_in_insert = true,
--   },
-- }
